#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:
exec-once = /usr/lib/hyprpolkitagent
exec-once = waybar
exec-once = hyprpaper
exec-once = swaync
exec-once = systemctl --user start hyprpolkitagent
exec-once = nm-applet --indicator
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

# Unlock KWallet on startup
exec-once = /usr/lib/pam_kwallet_init

exec-once = blueman-applet
# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox