windowrule = match:title ^(OPBounty)$, float on, center on, no_max_size on, render_unfocused on, focus_on_activate on
misc:render_unfocused_fps = 60
windowrule = match:class ^(gamescope)$, float on, center on, no_max_size on 