# Modern Hyprpaper Configuration

wallpaper {
    monitor = 
    path = ~/Pictures/wallpaper.jpg
    fit_mode = cover
}

# Disable the default hyprland anime mascot from spawning at the bottom
splash = false

# Enable IPC so we can change wallpapers on the fly from the terminal
ipc = true
